In [6]:
import os
import numpy as np

In [2]:
file_path = "/home/jovyan/sai-semocc1-workspace/practice/sereact/data/dl_challenge/8b061a8a-9915-11ee-9103-bbb8eae05561/calib.txt"

In [9]:
with open(file_path,'r') as f:
    lines = f.readlines()
    intrin = list(map(float,lines[0].split()))
    print(intrin)
    extrin = list(map(float,lines[1].split()))
    mat_k = np.array(intrin).reshape(3,3)
    mat_E = np.array(extrin).reshape(4,4)

print(mat_k)
print(mat_E)


[886.4093777018063, 0.0, 303.5, 0.0, 882.1595018665421, 240.5, 0.0, 0.0, 1.0]
[[886.4093777    0.         303.5       ]
 [  0.         882.15950187 240.5       ]
 [  0.           0.           1.        ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
